### ISSUE TITLE
The issue: javax.security.sasl.SaslException: User name could not be obtained [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback])

### ISSUE THREAD

**Issue by acdcjunior** [acdcjunior/kafka#1]
# Exception

Exception that gets logged:

```
14:44:53,392 ERROR [org.apache.kafka.clients.NetworkClient] (DomainEvents-1_KafkaConsumer) [Consumer clientId=DomainEvents-Consumer-Random#733322871839147346, groupId=cg-my-app] Connection to node -3 failed authentication due to: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: User name could not be obtained [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]) occurred when evaluating SASL token received from the Kafka Broker. Kafka Client will go to AUTHENTICATION_FAILED state.
14:44:53,398 WARN  [app.domainevents.KafkaDomainEventsConsumer] (DomainEvents-1_KafkaConsumer) Consumer stopped: org.apache.kafka.common.errors.SaslAuthenticationException: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: User name could not be obtained [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]) occurred when evaluating SASL token received from the Kafka Broker. Kafka Client will go to AUTHENTICATION_FAILED state.
Caused by: javax.security.sasl.SaslException: User name could not be obtained [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]
	at org.apache.kafka.common.security.scram.ScramSaslClient.evaluateChallenge(ScramSaslClient.java:105) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator$2.run(SaslClientAuthenticator.java:361) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator$2.run(SaslClientAuthenticator.java:359) [kafka-clients-1.1.1.jar:]
	at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.7.0_79]
	at javax.security.auth.Subject.doAs(Subject.java:415) [rt.jar:1.7.0_79]
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:359) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:269) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:206) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:81) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:486) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:424) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:261) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:209) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:219) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:205) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:279) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1149) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115) [kafka-clients-1.1.1.jar:]
	at app.domainevents.KafkaDomainEventsConsumer.consumerLoop(KafkaDomainEventsConsumer.java:119) [microlib-domain-events-1.0.0-beta-17-SPRING-4.17.jar:]
	at app.domainevents.KafkaDomainEventsConsumer.access$100(KafkaDomainEventsConsumer.java:31) [microlib-domain-events-1.0.0-beta-17-SPRING-4.17.jar:]
	at app.domainevents.KafkaDomainEventsConsumer$2.run(KafkaDomainEventsConsumer.java:107) [microlib-domain-events-1.0.0-beta-17-SPRING-4.17.jar:]
	at app.domainevents.KafkaDomainEventsConsumer$2.run(KafkaDomainEventsConsumer.java:104) [microlib-domain-events-1.0.0-beta-17-SPRING-4.17.jar:]
	at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.7.0_79]
	at app.domainevents.KafkaDomainEventsConsumer.iniciarConsumer(KafkaDomainEventsConsumer.java:104) [microlib-domain-events-1.0.0-beta-17-SPRING-4.17.jar:]
	at app.domainevents.KafkaDomainEventsConsumer.access$000(KafkaDomainEventsConsumer.java:31) [microlib-domain-events-1.0.0-beta-17-SPRING-4.17.jar:]
	at app.domainevents.KafkaDomainEventsConsumer$1.run(KafkaDomainEventsConsumer.java:83) [microlib-domain-events-1.0.0-beta-17-SPRING-4.17.jar:]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
Caused by: javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback
	at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:89) [kafka-clients-1.1.1.jar:]
	at org.apache.kafka.common.security.scram.ScramSaslClient.evaluateChallenge(ScramSaslClient.java:103) [kafka-clients-1.1.1.jar:]
	... 30 more
```

Relevant kafka-clients (v. 1.1.1) snippet:

```
            } else if (callback instanceof ScramExtensionsCallback) {
                ScramExtensionsCallback sc = (ScramExtensionsCallback) callback;
                if (!isKerberos && subject != null && !subject.getPublicCredentials(Map.class).isEmpty()) {
                    sc.extensions((Map<String, String>) subject.getPublicCredentials(Map.class).iterator().next());
                }
            }  else {
                throw new UnsupportedCallbackException(callback, "Unrecognized SASL ClientCallback");
            }
```

At that point, if you run in debug mode and place a breakpoint in the first line of the snippet above, you'll notice that `callback` is indeed an instance of `ScramExtensionsCallback`. The only issue is that its `ScramExtensionsCallback` is of a different class loader than  `ScramExtensionsCallback` at the current code is. Therefore, `instanceof` fails.

# Discussion

When:

> You have two web apps deployed to the same JVM. When the first is loaded, it creates a `Provider` and stores it (using `Security.addProvider(new ScramSaslClientProvider());`, see org/apache/kafka/common/security/scram/ScramLoginModule.java and org/apache/kafka/common/security/scram/ScramSaslClientProvider.java).
> All works fine.
> The problem is when the second app is loaded, it does not store a new `Provider` because there's one already there. So it fetches it. The provider creates a `callback` (see below) using its own class loader (that is, the first app's class loader), not the second app's class loader, which makes the `instanceof` fail (again, details below).

In org/apache/kafka/common/security/authenticator/SaslClientCallbackHandler.java, line 83:

    callback instanceof ScramExtensionsCallback

returns false even though, if you use the debugger, `callback` *is* an instance of `ScramExtensionsCallback`.

The problem is `callback` was created using a different class loader.

org/apache/kafka/common/security/authenticator/SaslClientAuthenticator.java creates the client:

            saslClient = createSaslClient(); // 139

But it uses:

    return Sasl.createSaslClient(mechs, clientPrincipalName, servicePrincipal, host, configs, callbackHandler);

Which gets the `Provider` from `java.security.Security`

   Provider[] provs = Security.getProviders(mechFilter);

**Comment by acdcjunior** [comment]
Fix patch:
![image](https://user-images.githubusercontent.com/5091082/87093037-e8d9a900-c212-11ea-8781-ab030e2288a0.png)
